# https://github.com/k1LoW/octocov
# https://zenn.dev/harachan/scraps/d2b8ec4f22aa09
# PRにテストカバレッジを図で表示する
coverage:
  paths:
    - coverage.out
codeToTestRatio:
  code:
    - './backend/**/*.go'
    - './backend/!**/*_test.go'
  test:
    - './backend/**/*_test.go'
testExecutionTime:
  if: true
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
comment:
  if: is_pull_request
report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}

# TODO: backend/配下に置きたいが，ファイルを検知してくれない