# https://reboooot.net/post/how-to-specify-mem-limit-on-docker/
# NOTE: esでmem_limitを指定したいため，v3.8→v2.2へ移行した
version: "2.2"
services:
# nginx
# frontend
# frontend-build
  api:
    build:
      context: ./backend
    environment:
      BASEAPP_ENV: dev
      PORT: 8000
      # https://dev.mysql.com/doc/refman/5.6/ja/connecting.html
      # MySQLサーバーが稼働しているホストの名前
      # https://www.itmanage.co.jp/column/host/#:~:text=%E3%83%9B%E3%82%B9%E3%83%88%E3%81%A8%E3%81%AF%E3%80%81%E3%82%B3%E3%83%B3%E3%83%94%E3%83%A5%E3%83%BC%E3%82%BF%E3%83%8D%E3%83%83%E3%83%88%E3%83%AF%E3%83%BC%E3%82%AF,%E6%8C%87%E5%AE%9A%E3%81%99%E3%82%8B%E5%BF%85%E8%A6%81%E3%81%8C%E3%81%82%E3%82%8A%E3%81%BE%E3%81%99%E3%80%82
      # host: コンピュータネットワークにおける接続されたコンピュータやデバイス（端末、周辺機器（サーバ、パソコン、スマートフォン、ルータ））の総称のこと
      #       ITネットワークの「ホスト」とは主にサーバサイドのサーバやネットワーク機器などが該当します。対する「ゲスト」はパソコンやスマートフォンなどのクライアントサイドにおけるコンピュータを示します。
      DB_HOST: baseapp-db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_DATABASE: baseapp
      REDIS_HOST: baseapp-redis
      REDIS_PORT: 6379
    command:
      # https://zenn.dev/hsaki/books/golang-httpserver-internal/viewer/serverstart
      # -r, --regex=[] : 監視するファイルやディレクトリを正規表現などで指定する
      # -s, --start-service=false:長時間起動するアプリかどうか．サーバーなど
      # https://qiita.com/ukinau/items/410f56b6d777ad1e4e90#dash-bash-zsh%E3%81%AE-c%E3%81%AE%E9%81%95%E3%81%84
      # sh -c : 渡されたコマンドを新しいshellプロセスの実行空間でそのまま実行
      # https://zenn.dev/keyamin/articles/4dbcce8f214bfe#%E3%82%B3%E3%83%9E%E3%83%B3%E3%83%89%E3%83%A9%E3%82%A4%E3%83%B3%E5%BC%95%E6%95%B0%E3%82%92%E5%8F%97%E3%81%91%E5%8F%96%E3%82%8B
      # flagで，コマンドライン引数から値を受け取る
      reflex -r '\.go$$' -s -- sh -c 'go run .'
    container_name: baseapp-api
    ports:
      # https://www.engilaboo.com/docker-compose-environment-default/
      - ${API_PORT:-18000}:8000
    volumes:
      - ./backend:/app
    working_dir: /app
  swagger-ui:
    # https://qiita.com/A-Kira/items/3d17396c7cc98873e29d
    image: swaggerapi/swagger-ui
    container_name: baseapp-swagger-ui
    depends_on:
      - api
    ports:
      # - "${SWAGGER_PORT:-18001}:8001"
      - 18080:8080
    volumes:
      - ./swagger/:/swagger
    environment:
      - SWAGGER_URL=./swagger.yaml
      - SWAGGER_JSON=/swagger/swagger.yaml
  db:
    image: mysql:8.0.29
    # https://qiita.com/toyoyuto618/items/f225e1b2ab22ca5adf33
    # platform: どのプラットフォーム (OSおよびCPUアーキテクチャの組み合わせ) に対応したイメージを生成するのかを指定
    # https://gihyo.jp/dev/serial/01/mysql-road-construction-news/0167
    #           M1Macのプラットフォームはarm64, mysqlイメージのサポートプラットフォームはamd64, M1の場合指定しないとlinux/arm64/v8対応のイメージをpullしようとしてエラーになる．
    platform: linux/amd64
    container_name: baseapp-db
    depends_on:
      - api
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: baseapp
      MYSQL_ROOT_PASSWORD: password
    volumes:
      # https://www.7key.jp/computer/linux/directory.html
      # /var/lib: アプリケーションやシステムが持つ、プログラム実行によって変更されたデータや特定のホスト情報に関る情報を置くディレクトリ
      - db-data:/var/lib/mysql
      # https://www.7key.jp/computer/linux/directory.html
      # /etc: プログラムの操作や制御を行う際に必要となる設定ファイルが /etc 階層に配置されます。関連する設定ファイルが多い場合は、/etc 配下にサブディレクトリを作成し、その中に配置する場合もあります。
      # https://docs.docker.jp/docker-for-mac/osxfs-caching.html#consistentcacheddelegated
      # cached: ホストの表示が信頼できる（ホスト上の更新がコンテナ上に反映するまで、遅延が発生するのを許容）
      - $PWD/_tools/mysql/conf.d:/etc/mysql/conf.d:cached
    ports:
      - "33306:3306"
  redis:
    image: redis:7.0.4
    container_name: baseapp-redis
    depends_on:
      - api
    ports:
      - "36379:6379"
    volumes:
      - redis-data:/data
  # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-file
  es:
    # TODO: DockerImageを切り分け，analyzerを設定する
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.1
    container_name: baseapp-es
    depends_on:
      - api
    ports:
      # NOTE: curlでの接続は9201, コンテナ間の接続は9200
      - ${ES_PORT:-9201}:9200
      - ${ES_PORT:-9301}:9300
    volumes:
      - es-data:/usr/share/elasticsearch/data
    mem_limit: 1073741824 # in bytes
    environment:
      # NOTE: 「single-node」 を指定しないと「bootstrap checks failed. You must address the points described in the following [2] lines before starting Elasticsearch.」エラー
      #       下記urlの「sudo sysctl -w vm.max_map_count=262144」を試したが，現状設定はできていない
      # https://hawksnowlog.blogspot.com/2022/05/run-elastic-search8-on-docker.html
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_windows_and_macos_with_docker_desktop
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      # 現状securityを明示的に無効化
      # % curl http://localhost:9201 → {"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication credentials for REST request [/]","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","ApiKey"]}}],"type":"security_exception","reason":"missing authentication credentials for REST request [/]","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","ApiKey"]}},"status":401}%
      # TODO: ローカルでも何かしらのsecurityを設ける
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
# migration
# adminer?
volumes:
  db-data:
  redis-data:
  es-data: