# # https://github.com/k1LoW/octocov
# # https://github.com/k1LoW/octocov-action
# on:
#   push:
#     branches:
#       - "main"
#   pull_request:
# name: test
# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/setup-go@v3
#       with:
#         go-version: '>=1.18'
#     - uses: actions/checkout@v3
#     # https://blog.takuchalle.dev/post/2020/02/20/github_actions_change_directory/
#     # &&　で繋ぐ
#     - run: cd backend/ && go test ./... -coverprofile=coverage.out
#     - name: report coverage
#       uses: k1LoW/octocov-action@v0